### ISSUE TITLE
Accessing frontend from remote location not working

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#20]
Currently, we can only access the frontend from **localhost** and not from another remote client.

Console.log:
> net::ERR_CONNECTION_REFUSED
localhost:8081/users?username=admin Failed to load resource: 

>UNCAUGHT
"Property set failed: object in path "session.session.messages" could not be found or was destroyed."

We need to fix this issue.

**Comment by czirkelbach** [comment]
TODO
Test in current development version.

**Comment by Alexander-Krause-Glau** [comment]
I will test this with a distributed backend based on multiple docker-compose files and the necessary environment variables. This "complex" setup can then be provided to users as well.

IMO testing Apache Tomcat + Frontend and Backend Jars running on different servers is not necessary, since we do not provide non-Docker environments for users anymore.

**Comment by Alexander-Krause-Glau** [comment]
Done.
