### ISSUE TITLE
Enhance application search

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-ui-frontend#28]
Enhance the search within the application perspective.
Ideas: auto-completion instead of first matching.

**Comment by Alexander-Krause-Glau** [comment]
@Malte-Hansen introduced a simple but synchronous solution to this problem in 890bfa0eaa0c443f64a135775412a3cfb5b229f1. This might work for our dummy landscape, but its runtime is dependent on the applications size, therefore will probably freeze the UI element (dunno if this is actually true).

I didn't tackle this enhancement, since I wanted to use the [Ember-Concurrency](http://ember-concurrency.com/docs/examples/autocomplete/) addon for an asynchronous data retrievement.

**Comment by Alexander-Krause-Glau** [comment]
Implemented an ember-concurrency version with ddfda6bd4366d99bb73d0cde8bbeb90eef10af5f. Still requires a bit of work as shown in the comments of the file.

**Comment by Alexander-Krause-Glau** [comment]
Added [ember-power-select](https://ember-power-select.com/). 

TODO

- [x] Apply CSS style of ExplorViz to this element https://ember-power-select.com/cookbook/css-animations
- [x] Show selected option in the element (somehow this is buggy and does not behave like the examples on the website)

**Comment by Alexander-Krause-Glau** [comment]
- [x] Remove arrow in input box
- [x] enable substring search via input pattern, e.g., `*i` would show explorviz

**Comment by Alexander-Krause-Glau** [comment]
Closed with ee1f482f7270c6c83ca2800a6fe8a84e2425be43

**Comment by Alexander-Krause-Glau** [comment]
Entitiy categories should be distinguished by using a delimeter. Something like:

```
------- Packages
X
Y
Z
------- Classes
X
Y
Z
```
